
package localhost.services.hrmservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-05-08T16:04:42.523+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class HrmServicePortType_HrmServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://localhost/services/HrmService", "HrmService");

    private HrmServicePortType_HrmServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HrmService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HrmService ss = new HrmService(wsdlURL, SERVICE_NAME);
        HrmServicePortType port = ss.getHrmServiceHttpPort();  
        
        {
        System.out.println("Invoking synHrmResource...");
        String _synHrmResource_in0 = "";
        String _synHrmResource_in1 = "";
        String _synHrmResource__return = port.synHrmResource(_synHrmResource_in0, _synHrmResource_in1);
        System.out.println("synHrmResource.result=" + _synHrmResource__return);


        }
        {
        System.out.println("Invoking checkUser...");
        String _checkUser_ipaddress = "";
        String _checkUser_loginid = "";
        String _checkUser_password = "";
        boolean _checkUser__return = port.checkUser(_checkUser_ipaddress, _checkUser_loginid, _checkUser_password);
        System.out.println("checkUser.result=" + _checkUser__return);


        }
        {
        System.out.println("Invoking getHrmDepartmentInfo...");
        String _getHrmDepartmentInfo_ipaddress = "";
        String _getHrmDepartmentInfo_subcompanyId = "";
        weaver.hrm.webservice.ArrayOfDepartmentBean _getHrmDepartmentInfo__return = port.getHrmDepartmentInfo(_getHrmDepartmentInfo_ipaddress, _getHrmDepartmentInfo_subcompanyId);
        System.out.println("getHrmDepartmentInfo.result=" + _getHrmDepartmentInfo__return);


        }
        {
        System.out.println("Invoking getHrmSubcompanyInfoXML...");
        String _getHrmSubcompanyInfoXML_in0 = "";
        String _getHrmSubcompanyInfoXML__return = port.getHrmSubcompanyInfoXML(_getHrmSubcompanyInfoXML_in0);
        System.out.println("getHrmSubcompanyInfoXML.result=" + _getHrmSubcompanyInfoXML__return);


        }
        {
        System.out.println("Invoking getHrmUserInfoXML...");
        String _getHrmUserInfoXML_in0 = "";
        String _getHrmUserInfoXML_in1 = "";
        String _getHrmUserInfoXML_in2 = "";
        String _getHrmUserInfoXML_in3 = "";
        String _getHrmUserInfoXML_in4 = "";
        String _getHrmUserInfoXML_in5 = "";
        String _getHrmUserInfoXML__return = port.getHrmUserInfoXML(_getHrmUserInfoXML_in0, _getHrmUserInfoXML_in1, _getHrmUserInfoXML_in2, _getHrmUserInfoXML_in3, _getHrmUserInfoXML_in4, _getHrmUserInfoXML_in5);
        System.out.println("getHrmUserInfoXML.result=" + _getHrmUserInfoXML__return);


        }
        {
        System.out.println("Invoking synJobtitle...");
        String _synJobtitle_in0 = "";
        String _synJobtitle_in1 = "";
        String _synJobtitle__return = port.synJobtitle(_synJobtitle_in0, _synJobtitle_in1);
        System.out.println("synJobtitle.result=" + _synJobtitle__return);


        }
        {
        System.out.println("Invoking getHrmDepartmentInfoXML...");
        String _getHrmDepartmentInfoXML_in0 = "";
        String _getHrmDepartmentInfoXML_in1 = "";
        String _getHrmDepartmentInfoXML__return = port.getHrmDepartmentInfoXML(_getHrmDepartmentInfoXML_in0, _getHrmDepartmentInfoXML_in1);
        System.out.println("getHrmDepartmentInfoXML.result=" + _getHrmDepartmentInfoXML__return);


        }
        {
        System.out.println("Invoking getHrmJobTitleInfoXML...");
        String _getHrmJobTitleInfoXML_in0 = "";
        String _getHrmJobTitleInfoXML_in1 = "";
        String _getHrmJobTitleInfoXML_in2 = "";
        String _getHrmJobTitleInfoXML__return = port.getHrmJobTitleInfoXML(_getHrmJobTitleInfoXML_in0, _getHrmJobTitleInfoXML_in1, _getHrmJobTitleInfoXML_in2);
        System.out.println("getHrmJobTitleInfoXML.result=" + _getHrmJobTitleInfoXML__return);


        }
        {
        System.out.println("Invoking changeUserPassword...");
        String _changeUserPassword_in0 = "";
        String _changeUserPassword_in1 = "";
        String _changeUserPassword_in2 = "";
        boolean _changeUserPassword__return = port.changeUserPassword(_changeUserPassword_in0, _changeUserPassword_in1, _changeUserPassword_in2);
        System.out.println("changeUserPassword.result=" + _changeUserPassword__return);


        }
        {
        System.out.println("Invoking synSubCompany...");
        String _synSubCompany_in0 = "";
        String _synSubCompany_in1 = "";
        String _synSubCompany__return = port.synSubCompany(_synSubCompany_in0, _synSubCompany_in1);
        System.out.println("synSubCompany.result=" + _synSubCompany__return);


        }
        {
        System.out.println("Invoking getHrmJobTitleInfo...");
        String _getHrmJobTitleInfo_ipaddress = "";
        String _getHrmJobTitleInfo_subcompanyId = "";
        String _getHrmJobTitleInfo_departmentid = "";
        weaver.hrm.webservice.ArrayOfJobTitleBean _getHrmJobTitleInfo__return = port.getHrmJobTitleInfo(_getHrmJobTitleInfo_ipaddress, _getHrmJobTitleInfo_subcompanyId, _getHrmJobTitleInfo_departmentid);
        System.out.println("getHrmJobTitleInfo.result=" + _getHrmJobTitleInfo__return);


        }
        {
        System.out.println("Invoking getHrmSubcompanyInfo...");
        String _getHrmSubcompanyInfo_ipaddress = "";
        weaver.hrm.webservice.ArrayOfSubCompanyBean _getHrmSubcompanyInfo__return = port.getHrmSubcompanyInfo(_getHrmSubcompanyInfo_ipaddress);
        System.out.println("getHrmSubcompanyInfo.result=" + _getHrmSubcompanyInfo__return);


        }
        {
        System.out.println("Invoking getHrmUserInfo...");
        String _getHrmUserInfo_ipaddress = "";
        String _getHrmUserInfo_loginid = "";
        String _getHrmUserInfo_subcompanyId = "";
        String _getHrmUserInfo_departmentid = "";
        String _getHrmUserInfo_jobtitleid = "";
        String _getHrmUserInfo_lastChangeDate = "";
        weaver.hrm.webservice.ArrayOfUserBean _getHrmUserInfo__return = port.getHrmUserInfo(_getHrmUserInfo_ipaddress, _getHrmUserInfo_loginid, _getHrmUserInfo_subcompanyId, _getHrmUserInfo_departmentid, _getHrmUserInfo_jobtitleid, _getHrmUserInfo_lastChangeDate);
        System.out.println("getHrmUserInfo.result=" + _getHrmUserInfo__return);


        }
        {
        System.out.println("Invoking synDepartment...");
        String _synDepartment_in0 = "";
        String _synDepartment_in1 = "";
        String _synDepartment__return = port.synDepartment(_synDepartment_in0, _synDepartment_in1);
        System.out.println("synDepartment.result=" + _synDepartment__return);


        }

        System.exit(0);
    }

}
