package com.sunnsoft.sloa.db.dao;

import com.sunnsoft.sloa.db.vo.AttachmentItem;
import org.gteam.db.dao.IBaseDAO;

import java.util.List;

// Generated by Hibernate Tools 3.4.0.CR1,modified by llade
/**
 * Home object for domain model class AttachmentItem.
 * @see com.sunnsoft.sloa.db.vo.AttachmentItem
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface AttachmentItemDAO extends IBaseDAO {


	public abstract  AttachmentItem findById( java.lang.Long id) ;
    
    public abstract  void save(AttachmentItem transientInstance) ;
    
	public abstract  void delete(AttachmentItem persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
