package com.sunnsoft.sloa.db.dao;
import org.gteam.db.dao.IBaseDAO;
import com.sunnsoft.sloa.db.vo.Mail;
// Generated by Hibernate Tools 3.4.0.CR1,modified by llade


import java.util.List;
/**
 * Home object for domain model class Mail.
 * @see com.sunnsoft.sloa.db.vo.Mail
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface MailDAO extends IBaseDAO {


	public abstract  Mail findById( java.lang.Long id) ;
    
    public abstract  void save(Mail transientInstance) ;
    
	public abstract  void delete(Mail persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
