package com.sunnsoft.sloa.db.dao;
import org.gteam.db.dao.IBaseDAO;
import com.sunnsoft.sloa.db.vo.Receive;
// Generated by Hibernate Tools 3.4.0.CR1,modified by llade


import java.util.List;
/**
 * Home object for domain model class Receive.
 * @see com.sunnsoft.sloa.db.vo.Receive
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface ReceiveDAO extends IBaseDAO {


	public abstract  Receive findById( java.lang.Long id) ;
    
    public abstract  void save(Receive transientInstance) ;
    
	public abstract  void delete(Receive persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
