package com.sunnsoft.sloa.db.dao;

import com.sunnsoft.sloa.db.vo.Role;
import org.gteam.db.dao.IBaseDAO;

import java.util.List;

// Generated by Hibernate Tools 3.4.0.CR1,modified by llade
/**
 * Home object for domain model class Role.
 * @see com.sunnsoft.sloa.db.vo.Role
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface RoleDAO extends IBaseDAO {


	public abstract  Role findById( java.lang.Long id) ;
    
    public abstract  void save(Role transientInstance) ;
    
	public abstract  void delete(Role persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
