package com.sunnsoft.sloa.db.dao;

import com.sunnsoft.sloa.db.vo.UpdateRecord;
import org.gteam.db.dao.IBaseDAO;

import java.util.List;

// Generated by Hibernate Tools 3.4.0.CR1,modified by llade
/**
 * Home object for domain model class UpdateRecord.
 * @see com.sunnsoft.sloa.db.vo.UpdateRecord
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface UpdateRecordDAO extends IBaseDAO {


	public abstract  UpdateRecord findById( java.lang.Long id) ;
    
    public abstract  void save(UpdateRecord transientInstance) ;
    
	public abstract  void delete(UpdateRecord persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
