package com.sunnsoft.sloa.db.dao;
import org.gteam.db.dao.IBaseDAO;
import com.sunnsoft.sloa.db.vo.User;
// Generated by Hibernate Tools 3.4.0.CR1,modified by llade


import java.util.List;
/**
 * Home object for domain model class User.
 * @see com.sunnsoft.sloa.db.vo.User
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface UserDAO extends IBaseDAO {


	public abstract  User findById( java.lang.Long id) ;
    
    public abstract  void save(User transientInstance) ;
    
	public abstract  void delete(User persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
