package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1



/**
 * Hrmdepartment generated by hbm2java
 */
public class Hrmdepartment  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:id
	*Comment:
	*/
     private int id;
	/**
	*Name:部门标识
	*Comment:
	*/
     private String departmentmark;
	/**
	*Name:部门名称
	*Comment:
	*/
     private String departmentname;
	/**
	*Name:所属分部1
	*Comment:
	*/
     private Integer subcompanyid1;
	/**
	*Name:上级部门id
	*Comment:
	*/
     private Integer supdepid;
	/**
	*Name:所有上级部门id
	*Comment:
	*/
     private String allsupdepid;
	/**
	*Name:显示顺序
	*Comment:
	*/
     private Integer showorder;
	/**
	*Name:封存标识
	*Comment:
	*/
     private Character canceled;
	/**
	*Name:部门编码
	*Comment:
	*/
     private String departmentcode;
	/**
	*Name:协办人
	*Comment:
	*/
     private Integer coadjutant;
	/**
	*Name:组织架构部门负责人
	*Comment:
	*/
     private String zzjgbmfzr;
	/**
	*Name:组织架构部门分管领导
	*Comment:
	*/
     private String zzjgbmfgld;
	/**
	*Name:矩阵管理部门负责人
	*Comment:
	*/
     private String jzglbmfzr;
	/**
	*Name:矩阵管理部门分管领导
	*Comment:
	*/
     private String jzglbmfgld;
	/**
	*Name:矩阵部门负责人员
	*Comment:
	*/
     private String bmfzr;
	/**
	*Name:矩阵部门分管领导
	*Comment:
	*/
     private String bmfgld;
	/**
	*Name:outkey
	*Comment:
	*/
     private String outkey;
	/**
	*Name:budgetatuomoveorder
	*Comment:
	*/
     private Integer budgetatuomoveorder;
	/**
	*Name:ecology_pinyin_search
	*Comment:
	*/
     private String ecologyPinyinSearch;
	/**
	*Name:tlevel
	*Comment:
	*/
     private Integer tlevel;

    public Hrmdepartment() {
    }

	
    public Hrmdepartment(int id) {
        this.id = id;
    }
    public Hrmdepartment(int id, String departmentmark, String departmentname, Integer subcompanyid1, Integer supdepid, String allsupdepid, Integer showorder, Character canceled, String departmentcode, Integer coadjutant, String zzjgbmfzr, String zzjgbmfgld, String jzglbmfzr, String jzglbmfgld, String bmfzr, String bmfgld, String outkey, Integer budgetatuomoveorder, String ecologyPinyinSearch, Integer tlevel) {
       this.id = id;
       this.departmentmark = departmentmark;
       this.departmentname = departmentname;
       this.subcompanyid1 = subcompanyid1;
       this.supdepid = supdepid;
       this.allsupdepid = allsupdepid;
       this.showorder = showorder;
       this.canceled = canceled;
       this.departmentcode = departmentcode;
       this.coadjutant = coadjutant;
       this.zzjgbmfzr = zzjgbmfzr;
       this.zzjgbmfgld = zzjgbmfgld;
       this.jzglbmfzr = jzglbmfzr;
       this.jzglbmfgld = jzglbmfgld;
       this.bmfzr = bmfzr;
       this.bmfgld = bmfgld;
       this.outkey = outkey;
       this.budgetatuomoveorder = budgetatuomoveorder;
       this.ecologyPinyinSearch = ecologyPinyinSearch;
       this.tlevel = tlevel;
    }
   
	/**
	*Name:id
	*Comment:
	*/
    public int getId() {
        return this.id;
    }
    
	/**
	*Name:id
	*Comment:
	*/
    public void setId(int id) {
        this.id = id;
    }
	/**
	*Name:部门标识
	*Comment:
	*/
    public String getDepartmentmark() {
        return this.departmentmark;
    }
    
	/**
	*Name:部门标识
	*Comment:
	*/
    public void setDepartmentmark(String departmentmark) {
        this.departmentmark = departmentmark;
    }
	/**
	*Name:部门名称
	*Comment:
	*/
    public String getDepartmentname() {
        return this.departmentname;
    }
    
	/**
	*Name:部门名称
	*Comment:
	*/
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname;
    }
	/**
	*Name:所属分部1
	*Comment:
	*/
    public Integer getSubcompanyid1() {
        return this.subcompanyid1;
    }
    
	/**
	*Name:所属分部1
	*Comment:
	*/
    public void setSubcompanyid1(Integer subcompanyid1) {
        this.subcompanyid1 = subcompanyid1;
    }
	/**
	*Name:上级部门id
	*Comment:
	*/
    public Integer getSupdepid() {
        return this.supdepid;
    }
    
	/**
	*Name:上级部门id
	*Comment:
	*/
    public void setSupdepid(Integer supdepid) {
        this.supdepid = supdepid;
    }
	/**
	*Name:所有上级部门id
	*Comment:
	*/
    public String getAllsupdepid() {
        return this.allsupdepid;
    }
    
	/**
	*Name:所有上级部门id
	*Comment:
	*/
    public void setAllsupdepid(String allsupdepid) {
        this.allsupdepid = allsupdepid;
    }
	/**
	*Name:显示顺序
	*Comment:
	*/
    public Integer getShoworder() {
        return this.showorder;
    }
    
	/**
	*Name:显示顺序
	*Comment:
	*/
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }
	/**
	*Name:封存标识
	*Comment:
	*/
    public Character getCanceled() {
        return this.canceled;
    }
    
	/**
	*Name:封存标识
	*Comment:
	*/
    public void setCanceled(Character canceled) {
        this.canceled = canceled;
    }
	/**
	*Name:部门编码
	*Comment:
	*/
    public String getDepartmentcode() {
        return this.departmentcode;
    }
    
	/**
	*Name:部门编码
	*Comment:
	*/
    public void setDepartmentcode(String departmentcode) {
        this.departmentcode = departmentcode;
    }
	/**
	*Name:协办人
	*Comment:
	*/
    public Integer getCoadjutant() {
        return this.coadjutant;
    }
    
	/**
	*Name:协办人
	*Comment:
	*/
    public void setCoadjutant(Integer coadjutant) {
        this.coadjutant = coadjutant;
    }
	/**
	*Name:组织架构部门负责人
	*Comment:
	*/
    public String getZzjgbmfzr() {
        return this.zzjgbmfzr;
    }
    
	/**
	*Name:组织架构部门负责人
	*Comment:
	*/
    public void setZzjgbmfzr(String zzjgbmfzr) {
        this.zzjgbmfzr = zzjgbmfzr;
    }
	/**
	*Name:组织架构部门分管领导
	*Comment:
	*/
    public String getZzjgbmfgld() {
        return this.zzjgbmfgld;
    }
    
	/**
	*Name:组织架构部门分管领导
	*Comment:
	*/
    public void setZzjgbmfgld(String zzjgbmfgld) {
        this.zzjgbmfgld = zzjgbmfgld;
    }
	/**
	*Name:矩阵管理部门负责人
	*Comment:
	*/
    public String getJzglbmfzr() {
        return this.jzglbmfzr;
    }
    
	/**
	*Name:矩阵管理部门负责人
	*Comment:
	*/
    public void setJzglbmfzr(String jzglbmfzr) {
        this.jzglbmfzr = jzglbmfzr;
    }
	/**
	*Name:矩阵管理部门分管领导
	*Comment:
	*/
    public String getJzglbmfgld() {
        return this.jzglbmfgld;
    }
    
	/**
	*Name:矩阵管理部门分管领导
	*Comment:
	*/
    public void setJzglbmfgld(String jzglbmfgld) {
        this.jzglbmfgld = jzglbmfgld;
    }
	/**
	*Name:矩阵部门负责人员
	*Comment:
	*/
    public String getBmfzr() {
        return this.bmfzr;
    }
    
	/**
	*Name:矩阵部门负责人员
	*Comment:
	*/
    public void setBmfzr(String bmfzr) {
        this.bmfzr = bmfzr;
    }
	/**
	*Name:矩阵部门分管领导
	*Comment:
	*/
    public String getBmfgld() {
        return this.bmfgld;
    }
    
	/**
	*Name:矩阵部门分管领导
	*Comment:
	*/
    public void setBmfgld(String bmfgld) {
        this.bmfgld = bmfgld;
    }
	/**
	*Name:outkey
	*Comment:
	*/
    public String getOutkey() {
        return this.outkey;
    }
    
	/**
	*Name:outkey
	*Comment:
	*/
    public void setOutkey(String outkey) {
        this.outkey = outkey;
    }
	/**
	*Name:budgetatuomoveorder
	*Comment:
	*/
    public Integer getBudgetatuomoveorder() {
        return this.budgetatuomoveorder;
    }
    
	/**
	*Name:budgetatuomoveorder
	*Comment:
	*/
    public void setBudgetatuomoveorder(Integer budgetatuomoveorder) {
        this.budgetatuomoveorder = budgetatuomoveorder;
    }
	/**
	*Name:ecology_pinyin_search
	*Comment:
	*/
    public String getEcologyPinyinSearch() {
        return this.ecologyPinyinSearch;
    }
    
	/**
	*Name:ecology_pinyin_search
	*Comment:
	*/
    public void setEcologyPinyinSearch(String ecologyPinyinSearch) {
        this.ecologyPinyinSearch = ecologyPinyinSearch;
    }
	/**
	*Name:tlevel
	*Comment:
	*/
    public Integer getTlevel() {
        return this.tlevel;
    }
    
	/**
	*Name:tlevel
	*Comment:
	*/
    public void setTlevel(Integer tlevel) {
        this.tlevel = tlevel;
    }




}


