package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Mail generated by hbm2java
 */
public class Mail  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:传阅id
	*Comment:传阅id
	*/
     private Long mailId;
	/**
	*Name:发件人id
	*Comment:发件人id
	*/
     private long userId;
	/**
	*Name:发件人工作编号
	*Comment:发件人工作编号
	*/
     private String workCode;
	/**
	*Name:发件人姓名
	*Comment:发件人的姓名
	*/
     private String lastName;
	/**
	*Name:发件人登录名
	*Comment:用户的登录名称(冗余字段)
	*/
     private String loginId;
	/**
	*Name:发件人的分部全称
	*Comment:发件人的分部全称
	*/
     private String subcompanyName;
	/**
	*Name:发件人的部门全称
	*Comment:发件人的部门全称
	*/
     private String departmentName;
	/**
	*Name:收件人名字
	*Comment:可以有多个(冗余字段)
	*/
     private String allReceiveName;
	/**
	*Name:传阅主题
	*Comment:传阅主题(不做限制)
	*/
     private String title;
	/**
	*Name:邮件内容
	*Comment:邮件内容
	*/
     private String mailContent;
	/**
	*Name:创建传阅的时间
	*Comment:创建传阅的时间
	*/
     private Date createTime;
	/**
	*Name:发送传阅的时间
	*Comment:发送传阅的时间
	*/
     private Date sendTime;
	/**
	*Name:传阅状态
	*Comment:0 无状态   1 待发传阅  7 已删除
	*/
     private Integer status;
	/**
	*Name:传阅流程状态
	*Comment:1 发阅中   3 已完成
	*/
     private Integer stepStatus;
	/**
	*Name:设置的完成时间
	*Comment:传阅完成的时间
	*/
     private Date completeTime;
	/**
	*Name:重要传阅
	*Comment:重要传阅
	*/
     private Boolean ifImportant;
	/**
	*Name:允许修订附件
	*Comment:允许修订附件
	*/
     private Boolean ifUpdate;
	/**
	*Name:允许上传附件
	*Comment:允许上传附件
	*/
     private Boolean ifUpload;
	/**
	*Name:开封已阅确认
	*Comment:开封已阅确认
	*/
     private Boolean ifRead;
	/**
	*Name:短信提醒
	*Comment:短信提醒
	*/
     private Boolean ifNotify;
	/**
	*Name:确认时提醒
	*Comment:确认时提醒
	*/
     private Boolean ifRemind;
	/**
	*Name:确认时提醒所有传阅对象
	*Comment:确认时提醒所有传阅对象
	*/
     private Boolean ifRemindAll;
	/**
	*Name:传阅密送
	*Comment:传阅密送(不用实现)
	*/
     private Boolean ifSecrecy;
	/**
	*Name:允许新添加人员
	*Comment:允许新添加人员
	*/
     private Boolean ifAdd;
	/**
	*Name:有序确认
	*Comment:有序确认(留个字段,不实现)
	*/
     private Boolean ifSequence;
	/**
	*Name:是否有附件
	*Comment:0 为没有 （false），1 为存在（true）
	*/
     private Boolean hasAttachment;
	/**
	*Name:是否启用软删除
	*Comment:0 为未删除（false），1 为 删除（true）
	*/
     private boolean enabled;
	/**
	*Name:是否关注
	*Comment:0 为未关注 （false），1 已关注（true）
	*/
     private Boolean attention;
	/**
	*Name:传阅规则
	*Comment:该字段用于记录选择的传阅规则的名字 ，已分号分隔 ；
	*/
     private String ruleName;
	/**
	*Name:删除传阅的时间
	*Comment:删除传阅的时间
	*/
     private Date deleteTime;
     private List<AttachmentItem> attachmentItems = new ArrayList<AttachmentItem>(0);
     private List<Receive> receives = new ArrayList<Receive>(0);
     private List<Discuss> discusses = new ArrayList<Discuss>(0);
     private List<UserCollection> userCollections = new ArrayList<UserCollection>(0);

    public Mail() {
    }

	
    public Mail(long userId, String title, String mailContent, boolean enabled) {
        this.userId = userId;
        this.title = title;
        this.mailContent = mailContent;
        this.enabled = enabled;
    }
    public Mail(long userId, String workCode, String lastName, String loginId, String subcompanyName, String departmentName, String allReceiveName, String title, String mailContent, Date createTime, Date sendTime, Integer status, Integer stepStatus, Date completeTime, Boolean ifImportant, Boolean ifUpdate, Boolean ifUpload, Boolean ifRead, Boolean ifNotify, Boolean ifRemind, Boolean ifRemindAll, Boolean ifSecrecy, Boolean ifAdd, Boolean ifSequence, Boolean hasAttachment, boolean enabled, Boolean attention, String ruleName, Date deleteTime, List<AttachmentItem> attachmentItems, List<Receive> receives, List<Discuss> discusses, List<UserCollection> userCollections) {
       this.userId = userId;
       this.workCode = workCode;
       this.lastName = lastName;
       this.loginId = loginId;
       this.subcompanyName = subcompanyName;
       this.departmentName = departmentName;
       this.allReceiveName = allReceiveName;
       this.title = title;
       this.mailContent = mailContent;
       this.createTime = createTime;
       this.sendTime = sendTime;
       this.status = status;
       this.stepStatus = stepStatus;
       this.completeTime = completeTime;
       this.ifImportant = ifImportant;
       this.ifUpdate = ifUpdate;
       this.ifUpload = ifUpload;
       this.ifRead = ifRead;
       this.ifNotify = ifNotify;
       this.ifRemind = ifRemind;
       this.ifRemindAll = ifRemindAll;
       this.ifSecrecy = ifSecrecy;
       this.ifAdd = ifAdd;
       this.ifSequence = ifSequence;
       this.hasAttachment = hasAttachment;
       this.enabled = enabled;
       this.attention = attention;
       this.ruleName = ruleName;
       this.deleteTime = deleteTime;
       this.attachmentItems = attachmentItems;
       this.receives = receives;
       this.discusses = discusses;
       this.userCollections = userCollections;
    }
   
	/**
	*Name:传阅id
	*Comment:传阅id
	*/
    public Long getMailId() {
        return this.mailId;
    }
    
	/**
	*Name:传阅id
	*Comment:传阅id
	*/
    public void setMailId(Long mailId) {
        this.mailId = mailId;
    }
	/**
	*Name:发件人id
	*Comment:发件人id
	*/
    public long getUserId() {
        return this.userId;
    }
    
	/**
	*Name:发件人id
	*Comment:发件人id
	*/
    public void setUserId(long userId) {
        this.userId = userId;
    }
	/**
	*Name:发件人工作编号
	*Comment:发件人工作编号
	*/
    public String getWorkCode() {
        return this.workCode;
    }
    
	/**
	*Name:发件人工作编号
	*Comment:发件人工作编号
	*/
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }
	/**
	*Name:发件人姓名
	*Comment:发件人的姓名
	*/
    public String getLastName() {
        return this.lastName;
    }
    
	/**
	*Name:发件人姓名
	*Comment:发件人的姓名
	*/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
	/**
	*Name:发件人登录名
	*Comment:用户的登录名称(冗余字段)
	*/
    public String getLoginId() {
        return this.loginId;
    }
    
	/**
	*Name:发件人登录名
	*Comment:用户的登录名称(冗余字段)
	*/
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
	/**
	*Name:发件人的分部全称
	*Comment:发件人的分部全称
	*/
    public String getSubcompanyName() {
        return this.subcompanyName;
    }
    
	/**
	*Name:发件人的分部全称
	*Comment:发件人的分部全称
	*/
    public void setSubcompanyName(String subcompanyName) {
        this.subcompanyName = subcompanyName;
    }
	/**
	*Name:发件人的部门全称
	*Comment:发件人的部门全称
	*/
    public String getDepartmentName() {
        return this.departmentName;
    }
    
	/**
	*Name:发件人的部门全称
	*Comment:发件人的部门全称
	*/
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
	/**
	*Name:收件人名字
	*Comment:可以有多个(冗余字段)
	*/
    public String getAllReceiveName() {
        return this.allReceiveName;
    }
    
	/**
	*Name:收件人名字
	*Comment:可以有多个(冗余字段)
	*/
    public void setAllReceiveName(String allReceiveName) {
        this.allReceiveName = allReceiveName;
    }
	/**
	*Name:传阅主题
	*Comment:传阅主题(不做限制)
	*/
    public String getTitle() {
        return this.title;
    }
    
	/**
	*Name:传阅主题
	*Comment:传阅主题(不做限制)
	*/
    public void setTitle(String title) {
        this.title = title;
    }
	/**
	*Name:邮件内容
	*Comment:邮件内容
	*/
    public String getMailContent() {
        return this.mailContent;
    }
    
	/**
	*Name:邮件内容
	*Comment:邮件内容
	*/
    public void setMailContent(String mailContent) {
        this.mailContent = mailContent;
    }
	/**
	*Name:创建传阅的时间
	*Comment:创建传阅的时间
	*/
    public Date getCreateTime() {
        return this.createTime;
    }
    
	/**
	*Name:创建传阅的时间
	*Comment:创建传阅的时间
	*/
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
	/**
	*Name:发送传阅的时间
	*Comment:发送传阅的时间
	*/
    public Date getSendTime() {
        return this.sendTime;
    }
    
	/**
	*Name:发送传阅的时间
	*Comment:发送传阅的时间
	*/
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
	/**
	*Name:传阅状态
	*Comment:0 无状态   1 待发传阅  7 已删除
	*/
    public Integer getStatus() {
        return this.status;
    }
    
	/**
	*Name:传阅状态
	*Comment:0 无状态   1 待发传阅  7 已删除
	*/
    public void setStatus(Integer status) {
        this.status = status;
    }
	/**
	*Name:传阅流程状态
	*Comment:1 发阅中   3 已完成
	*/
    public Integer getStepStatus() {
        return this.stepStatus;
    }
    
	/**
	*Name:传阅流程状态
	*Comment:1 发阅中   3 已完成
	*/
    public void setStepStatus(Integer stepStatus) {
        this.stepStatus = stepStatus;
    }
	/**
	*Name:设置的完成时间
	*Comment:传阅完成的时间
	*/
    public Date getCompleteTime() {
        return this.completeTime;
    }
    
	/**
	*Name:设置的完成时间
	*Comment:传阅完成的时间
	*/
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }
	/**
	*Name:重要传阅
	*Comment:重要传阅
	*/
    public Boolean getIfImportant() {
        return this.ifImportant;
    }
    
	/**
	*Name:重要传阅
	*Comment:重要传阅
	*/
    public void setIfImportant(Boolean ifImportant) {
        this.ifImportant = ifImportant;
    }
	/**
	*Name:允许修订附件
	*Comment:允许修订附件
	*/
    public Boolean getIfUpdate() {
        return this.ifUpdate;
    }
    
	/**
	*Name:允许修订附件
	*Comment:允许修订附件
	*/
    public void setIfUpdate(Boolean ifUpdate) {
        this.ifUpdate = ifUpdate;
    }
	/**
	*Name:允许上传附件
	*Comment:允许上传附件
	*/
    public Boolean getIfUpload() {
        return this.ifUpload;
    }
    
	/**
	*Name:允许上传附件
	*Comment:允许上传附件
	*/
    public void setIfUpload(Boolean ifUpload) {
        this.ifUpload = ifUpload;
    }
	/**
	*Name:开封已阅确认
	*Comment:开封已阅确认
	*/
    public Boolean getIfRead() {
        return this.ifRead;
    }
    
	/**
	*Name:开封已阅确认
	*Comment:开封已阅确认
	*/
    public void setIfRead(Boolean ifRead) {
        this.ifRead = ifRead;
    }
	/**
	*Name:短信提醒
	*Comment:短信提醒
	*/
    public Boolean getIfNotify() {
        return this.ifNotify;
    }
    
	/**
	*Name:短信提醒
	*Comment:短信提醒
	*/
    public void setIfNotify(Boolean ifNotify) {
        this.ifNotify = ifNotify;
    }
	/**
	*Name:确认时提醒
	*Comment:确认时提醒
	*/
    public Boolean getIfRemind() {
        return this.ifRemind;
    }
    
	/**
	*Name:确认时提醒
	*Comment:确认时提醒
	*/
    public void setIfRemind(Boolean ifRemind) {
        this.ifRemind = ifRemind;
    }
	/**
	*Name:确认时提醒所有传阅对象
	*Comment:确认时提醒所有传阅对象
	*/
    public Boolean getIfRemindAll() {
        return this.ifRemindAll;
    }
    
	/**
	*Name:确认时提醒所有传阅对象
	*Comment:确认时提醒所有传阅对象
	*/
    public void setIfRemindAll(Boolean ifRemindAll) {
        this.ifRemindAll = ifRemindAll;
    }
	/**
	*Name:传阅密送
	*Comment:传阅密送(不用实现)
	*/
    public Boolean getIfSecrecy() {
        return this.ifSecrecy;
    }
    
	/**
	*Name:传阅密送
	*Comment:传阅密送(不用实现)
	*/
    public void setIfSecrecy(Boolean ifSecrecy) {
        this.ifSecrecy = ifSecrecy;
    }
	/**
	*Name:允许新添加人员
	*Comment:允许新添加人员
	*/
    public Boolean getIfAdd() {
        return this.ifAdd;
    }
    
	/**
	*Name:允许新添加人员
	*Comment:允许新添加人员
	*/
    public void setIfAdd(Boolean ifAdd) {
        this.ifAdd = ifAdd;
    }
	/**
	*Name:有序确认
	*Comment:有序确认(留个字段,不实现)
	*/
    public Boolean getIfSequence() {
        return this.ifSequence;
    }
    
	/**
	*Name:有序确认
	*Comment:有序确认(留个字段,不实现)
	*/
    public void setIfSequence(Boolean ifSequence) {
        this.ifSequence = ifSequence;
    }
	/**
	*Name:是否有附件
	*Comment:0 为没有 （false），1 为存在（true）
	*/
    public Boolean getHasAttachment() {
        return this.hasAttachment;
    }
    
	/**
	*Name:是否有附件
	*Comment:0 为没有 （false），1 为存在（true）
	*/
    public void setHasAttachment(Boolean hasAttachment) {
        this.hasAttachment = hasAttachment;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
	/**
	*Name:是否启用软删除
	*Comment:0 为未删除（false），1 为 删除（true）
	*/
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
	/**
	*Name:是否关注
	*Comment:0 为未关注 （false），1 已关注（true）
	*/
    public Boolean getAttention() {
        return this.attention;
    }
    
	/**
	*Name:是否关注
	*Comment:0 为未关注 （false），1 已关注（true）
	*/
    public void setAttention(Boolean attention) {
        this.attention = attention;
    }
	/**
	*Name:传阅规则
	*Comment:该字段用于记录选择的传阅规则的名字 ，已分号分隔 ；
	*/
    public String getRuleName() {
        return this.ruleName;
    }
    
	/**
	*Name:传阅规则
	*Comment:该字段用于记录选择的传阅规则的名字 ，已分号分隔 ；
	*/
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }
	/**
	*Name:删除传阅的时间
	*Comment:删除传阅的时间
	*/
    public Date getDeleteTime() {
        return this.deleteTime;
    }
    
	/**
	*Name:删除传阅的时间
	*Comment:删除传阅的时间
	*/
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
    public List<AttachmentItem> getAttachmentItems() {
        return this.attachmentItems;
    }
    
    public void setAttachmentItems(List<AttachmentItem> attachmentItems) {
        this.attachmentItems = attachmentItems;
    }
    public List<Receive> getReceives() {
        return this.receives;
    }
    
    public void setReceives(List<Receive> receives) {
        this.receives = receives;
    }
    public List<Discuss> getDiscusses() {
        return this.discusses;
    }
    
    public void setDiscusses(List<Discuss> discusses) {
        this.discusses = discusses;
    }
    public List<UserCollection> getUserCollections() {
        return this.userCollections;
    }
    
    public void setUserCollections(List<UserCollection> userCollections) {
        this.userCollections = userCollections;
    }




}


