package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * PersistentLogins generated by hbm2java
 */
public class PersistentLogins  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:series
	*Comment:
	*/
     private String series;
	/**
	*Name:username
	*Comment:
	*/
     private String username;
	/**
	*Name:token
	*Comment:
	*/
     private String token;
	/**
	*Name:last_used
	*Comment:
	*/
     private Date lastUsed;

    public PersistentLogins() {
    }

    public PersistentLogins(String series, String username, String token, Date lastUsed) {
       this.series = series;
       this.username = username;
       this.token = token;
       this.lastUsed = lastUsed;
    }
   
	/**
	*Name:series
	*Comment:
	*/
    public String getSeries() {
        return this.series;
    }
    
	/**
	*Name:series
	*Comment:
	*/
    public void setSeries(String series) {
        this.series = series;
    }
	/**
	*Name:username
	*Comment:
	*/
    public String getUsername() {
        return this.username;
    }
    
	/**
	*Name:username
	*Comment:
	*/
    public void setUsername(String username) {
        this.username = username;
    }
	/**
	*Name:token
	*Comment:
	*/
    public String getToken() {
        return this.token;
    }
    
	/**
	*Name:token
	*Comment:
	*/
    public void setToken(String token) {
        this.token = token;
    }
	/**
	*Name:last_used
	*Comment:
	*/
    public Date getLastUsed() {
        return this.lastUsed;
    }
    
	/**
	*Name:last_used
	*Comment:
	*/
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }




}


