package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.List;
import java.util.*;

/**
 * Receive generated by hbm2java
 */
public class Receive  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:收件id
	*Comment:收件id
	*/
     private Long receiveId;
     private Mail mail;
	/**
	*Name:收件人id
	*Comment:收件人id
	*/
     private long userId;
	/**
	*Name:收件人工作编号
	*Comment:收件人工作编号
	*/
     private String workCode;
	/**
	*Name:收件人姓名
	*Comment:收件人的姓名
	*/
     private String lastName;
	/**
	*Name:收件人登录名
	*Comment:用户的登录名称(冗余字段)
	*/
     private String loginId;
	/**
	*Name:收件人的分部全称
	*Comment:收件人的分部全称
	*/
     private String subcompanyName;
	/**
	*Name:收件人的部门全称
	*Comment:收件人的部门全称
	*/
     private String departmentName;
	/**
	*Name:接收传阅的时间
	*Comment:接收传阅的时间
	*/
     private Date receiveTime;
	/**
	*Name:加入时间
	*Comment:添加联系人的时间
	*/
     private Date joinTime;
	/**
	*Name:状态
	*Comment:状态: 0 未开封  1 已开封  
	*/
     private int receiveStatus;
	/**
	*Name:传阅筛选状态
	*Comment:4 草稿  5 未读 6 已读  
	*/
     private Integer mailState;
	/**
	*Name:传阅流程状态
	*Comment:(冗余字段) 1 发阅中 2 待办传阅 3 已完成
	*/
     private Integer stepStatus;
	/**
	*Name:开封时间
	*Comment:记录打开传阅的时间
	*/
     private Date openTime;
	/**
	*Name:是否确认
	*Comment:false 未确认 true 已确认 (传阅开封, 不一定是传阅确认   但传阅确认必须是传阅开封
)
	*/
     private Boolean ifConfirm;
	/**
	*Name:确认时间
	*Comment:确认时间
	*/
     private Date affirmTime;
	/**
	*Name:确认信息备注
	*Comment:当收到传阅后, 需要对收到的传阅进行确认, 同时要给出确认信息备注
	*/
     private String remark;
	/**
	*Name:确认/标识
	*Comment:该字段用于记录收件人在确认传阅时的  确认信息 + 确认时间 
	*/
     private String confirmRecord;
	/**
	*Name:序号
	*Comment:序号
	*/
     private Integer serialNum;
	/**
	*Name:是否重新确认
	*Comment:该字段用于重新确认传阅, false 未重新确认 true 重新确认 
	*/
     private Boolean afreshConfim;
	/**
	*Name:(重新)确认/标识
	*Comment:该字段用于记录收件人在重新 确认传阅时的  确认信息 + 确认时间 
	*/
     private String acRecord;
	/**
	*Name:(重新)确认信息备注
	*Comment:当收到传阅后, 需要对收到的传阅进行确认, 同时要给出确认信息备注(重新)
	*/
     private String afreshRemark;
	/**
	*Name:(重新)确认时间
	*Comment:确认时间(重新)
	*/
     private Date mhTime;
	/**
	*Name:是否关注
	*Comment:收件人的关注状态:  0 为未关注 （false），1 已关注（true）
	*/
     private Boolean receiveAttention;
	/**
	*Name:区别
	*Comment:区别是谁添加的联系人, 存放添加该联系人的用户ID
	*/
     private Long reDifferentiate;
     private List<UpdateRecord> updateRecords = new ArrayList<UpdateRecord>(0);

    public Receive() {
    }

	
    public Receive(long userId, int receiveStatus) {
        this.userId = userId;
        this.receiveStatus = receiveStatus;
    }
    public Receive(Mail mail, long userId, String workCode, String lastName, String loginId, String subcompanyName, String departmentName, Date receiveTime, Date joinTime, int receiveStatus, Integer mailState, Integer stepStatus, Date openTime, Boolean ifConfirm, Date affirmTime, String remark, String confirmRecord, Integer serialNum, Boolean afreshConfim, String acRecord, String afreshRemark, Date mhTime, Boolean receiveAttention, Long reDifferentiate, List<UpdateRecord> updateRecords) {
       this.mail = mail;
       this.userId = userId;
       this.workCode = workCode;
       this.lastName = lastName;
       this.loginId = loginId;
       this.subcompanyName = subcompanyName;
       this.departmentName = departmentName;
       this.receiveTime = receiveTime;
       this.joinTime = joinTime;
       this.receiveStatus = receiveStatus;
       this.mailState = mailState;
       this.stepStatus = stepStatus;
       this.openTime = openTime;
       this.ifConfirm = ifConfirm;
       this.affirmTime = affirmTime;
       this.remark = remark;
       this.confirmRecord = confirmRecord;
       this.serialNum = serialNum;
       this.afreshConfim = afreshConfim;
       this.acRecord = acRecord;
       this.afreshRemark = afreshRemark;
       this.mhTime = mhTime;
       this.receiveAttention = receiveAttention;
       this.reDifferentiate = reDifferentiate;
       this.updateRecords = updateRecords;
    }
   
	/**
	*Name:收件id
	*Comment:收件id
	*/
    public Long getReceiveId() {
        return this.receiveId;
    }
    
	/**
	*Name:收件id
	*Comment:收件id
	*/
    public void setReceiveId(Long receiveId) {
        this.receiveId = receiveId;
    }
    public Mail getMail() {
        return this.mail;
    }
    
    public void setMail(Mail mail) {
        this.mail = mail;
    }
	/**
	*Name:收件人id
	*Comment:收件人id
	*/
    public long getUserId() {
        return this.userId;
    }
    
	/**
	*Name:收件人id
	*Comment:收件人id
	*/
    public void setUserId(long userId) {
        this.userId = userId;
    }
	/**
	*Name:收件人工作编号
	*Comment:收件人工作编号
	*/
    public String getWorkCode() {
        return this.workCode;
    }
    
	/**
	*Name:收件人工作编号
	*Comment:收件人工作编号
	*/
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }
	/**
	*Name:收件人姓名
	*Comment:收件人的姓名
	*/
    public String getLastName() {
        return this.lastName;
    }
    
	/**
	*Name:收件人姓名
	*Comment:收件人的姓名
	*/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
	/**
	*Name:收件人登录名
	*Comment:用户的登录名称(冗余字段)
	*/
    public String getLoginId() {
        return this.loginId;
    }
    
	/**
	*Name:收件人登录名
	*Comment:用户的登录名称(冗余字段)
	*/
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
	/**
	*Name:收件人的分部全称
	*Comment:收件人的分部全称
	*/
    public String getSubcompanyName() {
        return this.subcompanyName;
    }
    
	/**
	*Name:收件人的分部全称
	*Comment:收件人的分部全称
	*/
    public void setSubcompanyName(String subcompanyName) {
        this.subcompanyName = subcompanyName;
    }
	/**
	*Name:收件人的部门全称
	*Comment:收件人的部门全称
	*/
    public String getDepartmentName() {
        return this.departmentName;
    }
    
	/**
	*Name:收件人的部门全称
	*Comment:收件人的部门全称
	*/
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
	/**
	*Name:接收传阅的时间
	*Comment:接收传阅的时间
	*/
    public Date getReceiveTime() {
        return this.receiveTime;
    }
    
	/**
	*Name:接收传阅的时间
	*Comment:接收传阅的时间
	*/
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }
	/**
	*Name:加入时间
	*Comment:添加联系人的时间
	*/
    public Date getJoinTime() {
        return this.joinTime;
    }
    
	/**
	*Name:加入时间
	*Comment:添加联系人的时间
	*/
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }
	/**
	*Name:状态
	*Comment:状态: 0 未开封  1 已开封  
	*/
    public int getReceiveStatus() {
        return this.receiveStatus;
    }
    
	/**
	*Name:状态
	*Comment:状态: 0 未开封  1 已开封  
	*/
    public void setReceiveStatus(int receiveStatus) {
        this.receiveStatus = receiveStatus;
    }
	/**
	*Name:传阅筛选状态
	*Comment:4 草稿  5 未读 6 已读  
	*/
    public Integer getMailState() {
        return this.mailState;
    }
    
	/**
	*Name:传阅筛选状态
	*Comment:4 草稿  5 未读 6 已读  
	*/
    public void setMailState(Integer mailState) {
        this.mailState = mailState;
    }
	/**
	*Name:传阅流程状态
	*Comment:(冗余字段) 1 发阅中 2 待办传阅 3 已完成
	*/
    public Integer getStepStatus() {
        return this.stepStatus;
    }
    
	/**
	*Name:传阅流程状态
	*Comment:(冗余字段) 1 发阅中 2 待办传阅 3 已完成
	*/
    public void setStepStatus(Integer stepStatus) {
        this.stepStatus = stepStatus;
    }
	/**
	*Name:开封时间
	*Comment:记录打开传阅的时间
	*/
    public Date getOpenTime() {
        return this.openTime;
    }
    
	/**
	*Name:开封时间
	*Comment:记录打开传阅的时间
	*/
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }
	/**
	*Name:是否确认
	*Comment:false 未确认 true 已确认 (传阅开封, 不一定是传阅确认   但传阅确认必须是传阅开封
)
	*/
    public Boolean getIfConfirm() {
        return this.ifConfirm;
    }
    
	/**
	*Name:是否确认
	*Comment:false 未确认 true 已确认 (传阅开封, 不一定是传阅确认   但传阅确认必须是传阅开封
)
	*/
    public void setIfConfirm(Boolean ifConfirm) {
        this.ifConfirm = ifConfirm;
    }
	/**
	*Name:确认时间
	*Comment:确认时间
	*/
    public Date getAffirmTime() {
        return this.affirmTime;
    }
    
	/**
	*Name:确认时间
	*Comment:确认时间
	*/
    public void setAffirmTime(Date affirmTime) {
        this.affirmTime = affirmTime;
    }
	/**
	*Name:确认信息备注
	*Comment:当收到传阅后, 需要对收到的传阅进行确认, 同时要给出确认信息备注
	*/
    public String getRemark() {
        return this.remark;
    }
    
	/**
	*Name:确认信息备注
	*Comment:当收到传阅后, 需要对收到的传阅进行确认, 同时要给出确认信息备注
	*/
    public void setRemark(String remark) {
        this.remark = remark;
    }
	/**
	*Name:确认/标识
	*Comment:该字段用于记录收件人在确认传阅时的  确认信息 + 确认时间 
	*/
    public String getConfirmRecord() {
        return this.confirmRecord;
    }
    
	/**
	*Name:确认/标识
	*Comment:该字段用于记录收件人在确认传阅时的  确认信息 + 确认时间 
	*/
    public void setConfirmRecord(String confirmRecord) {
        this.confirmRecord = confirmRecord;
    }
	/**
	*Name:序号
	*Comment:序号
	*/
    public Integer getSerialNum() {
        return this.serialNum;
    }
    
	/**
	*Name:序号
	*Comment:序号
	*/
    public void setSerialNum(Integer serialNum) {
        this.serialNum = serialNum;
    }
	/**
	*Name:是否重新确认
	*Comment:该字段用于重新确认传阅, false 未重新确认 true 重新确认 
	*/
    public Boolean getAfreshConfim() {
        return this.afreshConfim;
    }
    
	/**
	*Name:是否重新确认
	*Comment:该字段用于重新确认传阅, false 未重新确认 true 重新确认 
	*/
    public void setAfreshConfim(Boolean afreshConfim) {
        this.afreshConfim = afreshConfim;
    }
	/**
	*Name:(重新)确认/标识
	*Comment:该字段用于记录收件人在重新 确认传阅时的  确认信息 + 确认时间 
	*/
    public String getAcRecord() {
        return this.acRecord;
    }
    
	/**
	*Name:(重新)确认/标识
	*Comment:该字段用于记录收件人在重新 确认传阅时的  确认信息 + 确认时间 
	*/
    public void setAcRecord(String acRecord) {
        this.acRecord = acRecord;
    }
	/**
	*Name:(重新)确认信息备注
	*Comment:当收到传阅后, 需要对收到的传阅进行确认, 同时要给出确认信息备注(重新)
	*/
    public String getAfreshRemark() {
        return this.afreshRemark;
    }
    
	/**
	*Name:(重新)确认信息备注
	*Comment:当收到传阅后, 需要对收到的传阅进行确认, 同时要给出确认信息备注(重新)
	*/
    public void setAfreshRemark(String afreshRemark) {
        this.afreshRemark = afreshRemark;
    }
	/**
	*Name:(重新)确认时间
	*Comment:确认时间(重新)
	*/
    public Date getMhTime() {
        return this.mhTime;
    }
    
	/**
	*Name:(重新)确认时间
	*Comment:确认时间(重新)
	*/
    public void setMhTime(Date mhTime) {
        this.mhTime = mhTime;
    }
	/**
	*Name:是否关注
	*Comment:收件人的关注状态:  0 为未关注 （false），1 已关注（true）
	*/
    public Boolean getReceiveAttention() {
        return this.receiveAttention;
    }
    
	/**
	*Name:是否关注
	*Comment:收件人的关注状态:  0 为未关注 （false），1 已关注（true）
	*/
    public void setReceiveAttention(Boolean receiveAttention) {
        this.receiveAttention = receiveAttention;
    }
	/**
	*Name:区别
	*Comment:区别是谁添加的联系人, 存放添加该联系人的用户ID
	*/
    public Long getReDifferentiate() {
        return this.reDifferentiate;
    }
    
	/**
	*Name:区别
	*Comment:区别是谁添加的联系人, 存放添加该联系人的用户ID
	*/
    public void setReDifferentiate(Long reDifferentiate) {
        this.reDifferentiate = reDifferentiate;
    }
    public List<UpdateRecord> getUpdateRecords() {
        return this.updateRecords;
    }
    
    public void setUpdateRecords(List<UpdateRecord> updateRecords) {
        this.updateRecords = updateRecords;
    }




}


