package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * SystemLog generated by hbm2java
 */
public class SystemLog  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:ID
	*Comment:
	*/
     private Long logId;
	/**
	*Name:操作人
	*Comment:可阅读的操作人信息，一般当前用户的昵称。也可以是用户真是姓名，试系统情况确定。
	*/
     private String operator;
	/**
	*Name:日志时间
	*Comment:
	*/
     private Date logTime;
	/**
	*Name:操作
	*Comment:
	*/
     private String action;
	/**
	*Name:ip地址
	*Comment:
	*/
     private String ip;
	/**
	*Name:身份信息
	*Comment:可以是用户名，用户实体id，session id等描述用户的信息，以便核对。
不和用户表直接外键关联。
	*/
     private String identityInfo;

    public SystemLog() {
    }

	
    public SystemLog(Date logTime, String action, String ip) {
        this.logTime = logTime;
        this.action = action;
        this.ip = ip;
    }
    public SystemLog(String operator, Date logTime, String action, String ip, String identityInfo) {
       this.operator = operator;
       this.logTime = logTime;
       this.action = action;
       this.ip = ip;
       this.identityInfo = identityInfo;
    }
   
	/**
	*Name:ID
	*Comment:
	*/
    public Long getLogId() {
        return this.logId;
    }
    
	/**
	*Name:ID
	*Comment:
	*/
    public void setLogId(Long logId) {
        this.logId = logId;
    }
	/**
	*Name:操作人
	*Comment:可阅读的操作人信息，一般当前用户的昵称。也可以是用户真是姓名，试系统情况确定。
	*/
    public String getOperator() {
        return this.operator;
    }
    
	/**
	*Name:操作人
	*Comment:可阅读的操作人信息，一般当前用户的昵称。也可以是用户真是姓名，试系统情况确定。
	*/
    public void setOperator(String operator) {
        this.operator = operator;
    }
	/**
	*Name:日志时间
	*Comment:
	*/
    public Date getLogTime() {
        return this.logTime;
    }
    
	/**
	*Name:日志时间
	*Comment:
	*/
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
	/**
	*Name:操作
	*Comment:
	*/
    public String getAction() {
        return this.action;
    }
    
	/**
	*Name:操作
	*Comment:
	*/
    public void setAction(String action) {
        this.action = action;
    }
	/**
	*Name:ip地址
	*Comment:
	*/
    public String getIp() {
        return this.ip;
    }
    
	/**
	*Name:ip地址
	*Comment:
	*/
    public void setIp(String ip) {
        this.ip = ip;
    }
	/**
	*Name:身份信息
	*Comment:可以是用户名，用户实体id，session id等描述用户的信息，以便核对。
不和用户表直接外键关联。
	*/
    public String getIdentityInfo() {
        return this.identityInfo;
    }
    
	/**
	*Name:身份信息
	*Comment:可以是用户名，用户实体id，session id等描述用户的信息，以便核对。
不和用户表直接外键关联。
	*/
    public void setIdentityInfo(String identityInfo) {
        this.identityInfo = identityInfo;
    }




}


