package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * UserMssage generated by hbm2java
 */
public class UserMssage  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:用户信息id
	*Comment:用户信息ID
	*/
     private Long userMssageId;
	/**
	*Name:用户ID
	*Comment:用户ID
	*/
     private Integer userId;
	/**
	*Name:用户编号
	*Comment:用户工作编号
	*/
     private String workCode;
	/**
	*Name:用户姓名
	*Comment:用户的姓名
	*/
     private String lastName;
	/**
	*Name:用户登录名
	*Comment:系统账号(登录名)
	*/
     private String loginId;
	/**
	*Name:部门全称
	*Comment:部门全称
	*/
     private String deptFullname;
	/**
	*Name:分部全称
	*Comment:分部全称
	*/
     private String fullName;
	/**
	*Name:用户部门ID
	*Comment:用户部门ID
	*/
     private String departmentId;
	/**
	*Name:用户分部ID
	*Comment:用户分部ID
	*/
     private String subcompanyId1;
	/**
	*Name:用户状态
	*Comment:用户状态
	*/
     private String status;
	/**
	*Name:显示顺序
	*Comment:显示顺序
	*/
     private Float dsporder;
	/**
	*Name:网盘session
	*Comment:网盘session
	*/
     private String boxSession;
	/**
	*Name:创建时间
	*Comment:创建时间
	*/
     private Date createTime;
	/**
	*Name:更新时间
	*Comment:更新时间
	*/
     private Date updateTime;

    public UserMssage() {
    }

    public UserMssage(Integer userId, String workCode, String lastName, String loginId, String deptFullname, String fullName, String departmentId, String subcompanyId1, String status, Float dsporder, String boxSession, Date createTime, Date updateTime) {
       this.userId = userId;
       this.workCode = workCode;
       this.lastName = lastName;
       this.loginId = loginId;
       this.deptFullname = deptFullname;
       this.fullName = fullName;
       this.departmentId = departmentId;
       this.subcompanyId1 = subcompanyId1;
       this.status = status;
       this.dsporder = dsporder;
       this.boxSession = boxSession;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
	/**
	*Name:用户信息id
	*Comment:用户信息ID
	*/
    public Long getUserMssageId() {
        return this.userMssageId;
    }
    
	/**
	*Name:用户信息id
	*Comment:用户信息ID
	*/
    public void setUserMssageId(Long userMssageId) {
        this.userMssageId = userMssageId;
    }
	/**
	*Name:用户ID
	*Comment:用户ID
	*/
    public Integer getUserId() {
        return this.userId;
    }
    
	/**
	*Name:用户ID
	*Comment:用户ID
	*/
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
	/**
	*Name:用户编号
	*Comment:用户工作编号
	*/
    public String getWorkCode() {
        return this.workCode;
    }
    
	/**
	*Name:用户编号
	*Comment:用户工作编号
	*/
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }
	/**
	*Name:用户姓名
	*Comment:用户的姓名
	*/
    public String getLastName() {
        return this.lastName;
    }
    
	/**
	*Name:用户姓名
	*Comment:用户的姓名
	*/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
	/**
	*Name:用户登录名
	*Comment:系统账号(登录名)
	*/
    public String getLoginId() {
        return this.loginId;
    }
    
	/**
	*Name:用户登录名
	*Comment:系统账号(登录名)
	*/
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
	/**
	*Name:部门全称
	*Comment:部门全称
	*/
    public String getDeptFullname() {
        return this.deptFullname;
    }
    
	/**
	*Name:部门全称
	*Comment:部门全称
	*/
    public void setDeptFullname(String deptFullname) {
        this.deptFullname = deptFullname;
    }
	/**
	*Name:分部全称
	*Comment:分部全称
	*/
    public String getFullName() {
        return this.fullName;
    }
    
	/**
	*Name:分部全称
	*Comment:分部全称
	*/
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
	/**
	*Name:用户部门ID
	*Comment:用户部门ID
	*/
    public String getDepartmentId() {
        return this.departmentId;
    }
    
	/**
	*Name:用户部门ID
	*Comment:用户部门ID
	*/
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
	/**
	*Name:用户分部ID
	*Comment:用户分部ID
	*/
    public String getSubcompanyId1() {
        return this.subcompanyId1;
    }
    
	/**
	*Name:用户分部ID
	*Comment:用户分部ID
	*/
    public void setSubcompanyId1(String subcompanyId1) {
        this.subcompanyId1 = subcompanyId1;
    }
	/**
	*Name:用户状态
	*Comment:用户状态
	*/
    public String getStatus() {
        return this.status;
    }
    
	/**
	*Name:用户状态
	*Comment:用户状态
	*/
    public void setStatus(String status) {
        this.status = status;
    }
	/**
	*Name:显示顺序
	*Comment:显示顺序
	*/
    public Float getDsporder() {
        return this.dsporder;
    }
    
	/**
	*Name:显示顺序
	*Comment:显示顺序
	*/
    public void setDsporder(Float dsporder) {
        this.dsporder = dsporder;
    }
	/**
	*Name:网盘session
	*Comment:网盘session
	*/
    public String getBoxSession() {
        return this.boxSession;
    }
    
	/**
	*Name:网盘session
	*Comment:网盘session
	*/
    public void setBoxSession(String boxSession) {
        this.boxSession = boxSession;
    }
	/**
	*Name:创建时间
	*Comment:创建时间
	*/
    public Date getCreateTime() {
        return this.createTime;
    }
    
	/**
	*Name:创建时间
	*Comment:创建时间
	*/
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
	/**
	*Name:更新时间
	*Comment:更新时间
	*/
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
	/**
	*Name:更新时间
	*Comment:更新时间
	*/
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


