package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.List;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:角色ID
	*Comment:
	*/
     private Long roleId;
     private Role role;
	/**
	*Name:角色名称
	*Comment:
	*/
     private String roleName;
	/**
	*Name:角色描述
	*Comment:
	*/
     private String roleDescription;
	/**
	*Name:状态
	*Comment:0 为失效 （false），1 为正常（true）
	*/
     private Boolean status;
     private List<User> users = new ArrayList<User>(0);
     private List<Menu> menus = new ArrayList<Menu>(0);
     private List<Role> roles = new ArrayList<Role>(0);

    public Role() {
    }

	
    public Role(String roleName) {
        this.roleName = roleName;
    }
    public Role(Role role, String roleName, String roleDescription, Boolean status, List<User> users, List<Menu> menus, List<Role> roles) {
       this.role = role;
       this.roleName = roleName;
       this.roleDescription = roleDescription;
       this.status = status;
       this.users = users;
       this.menus = menus;
       this.roles = roles;
    }
   
	/**
	*Name:角色ID
	*Comment:
	*/
    public Long getRoleId() {
        return this.roleId;
    }
    
	/**
	*Name:角色ID
	*Comment:
	*/
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
	/**
	*Name:角色名称
	*Comment:
	*/
    public String getRoleName() {
        return this.roleName;
    }
    
	/**
	*Name:角色名称
	*Comment:
	*/
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
	/**
	*Name:角色描述
	*Comment:
	*/
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
	/**
	*Name:角色描述
	*Comment:
	*/
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
	/**
	*Name:状态
	*Comment:0 为失效 （false），1 为正常（true）
	*/
    public Boolean getStatus() {
        return this.status;
    }
    
	/**
	*Name:状态
	*Comment:0 为失效 （false），1 为正常（true）
	*/
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public List<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(List<User> users) {
        this.users = users;
    }
    public List<Menu> getMenus() {
        return this.menus;
    }
    
    public void setMenus(List<Menu> menus) {
        this.menus = menus;
    }
    public List<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }




}


