package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.List;
import java.util.*;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:用户ID
	*Comment:
	*/
     private Long userId;
	/**
	*Name:登录名
	*Comment:
	*/
     private String accountName;
	/**
	*Name:昵称
	*Comment:
	*/
     private String nickName;
	/**
	*Name:创建日期
	*Comment:
	*/
     private Date createTime;
	/**
	*Name:密码
	*Comment:
	*/
     private String userPassword;
	/**
	*Name:是否管理员
	*Comment:
	*/
     private boolean admin;
	/**
	*Name:是否启用
	*Comment:0 为失效 （false），1 为正常（true）
	*/
     private boolean enabled;
	/**
	*Name:最后登录时间
	*Comment:
	*/
     private Date lastLogin;
	/**
	*Name:优先级
	*Comment:
	*/
     private int priority;
	/**
	*Name:是否软删除
	*Comment:
	*/
     private boolean softDelete;
	/**
	*Name:登录令牌
	*Comment:
	*/
     private String accessToken;
	/**
	*Name:令牌失效时间
	*Comment:
	*/
     private Date accessTokenExpire;
     private UserInfo userInfo;
     private List<Role> roles = new ArrayList<Role>(0);

    public User() {
    }

	
    public User(String accountName, Date createTime, String userPassword, boolean admin, boolean enabled, int priority, boolean softDelete) {
        this.accountName = accountName;
        this.createTime = createTime;
        this.userPassword = userPassword;
        this.admin = admin;
        this.enabled = enabled;
        this.priority = priority;
        this.softDelete = softDelete;
    }
    public User(String accountName, String nickName, Date createTime, String userPassword, boolean admin, boolean enabled, Date lastLogin, int priority, boolean softDelete, String accessToken, Date accessTokenExpire, UserInfo userInfo, List<Role> roles) {
       this.accountName = accountName;
       this.nickName = nickName;
       this.createTime = createTime;
       this.userPassword = userPassword;
       this.admin = admin;
       this.enabled = enabled;
       this.lastLogin = lastLogin;
       this.priority = priority;
       this.softDelete = softDelete;
       this.accessToken = accessToken;
       this.accessTokenExpire = accessTokenExpire;
       this.userInfo = userInfo;
       this.roles = roles;
    }
   
	/**
	*Name:用户ID
	*Comment:
	*/
    public Long getUserId() {
        return this.userId;
    }
    
	/**
	*Name:用户ID
	*Comment:
	*/
    public void setUserId(Long userId) {
        this.userId = userId;
    }
	/**
	*Name:登录名
	*Comment:
	*/
    public String getAccountName() {
        return this.accountName;
    }
    
	/**
	*Name:登录名
	*Comment:
	*/
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
	/**
	*Name:昵称
	*Comment:
	*/
    public String getNickName() {
        return this.nickName;
    }
    
	/**
	*Name:昵称
	*Comment:
	*/
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
	/**
	*Name:创建日期
	*Comment:
	*/
    public Date getCreateTime() {
        return this.createTime;
    }
    
	/**
	*Name:创建日期
	*Comment:
	*/
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
	/**
	*Name:密码
	*Comment:
	*/
    public String getUserPassword() {
        return this.userPassword;
    }
    
	/**
	*Name:密码
	*Comment:
	*/
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
	/**
	*Name:是否管理员
	*Comment:
	*/
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
	/**
	*Name:是否启用
	*Comment:0 为失效 （false），1 为正常（true）
	*/
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
	/**
	*Name:最后登录时间
	*Comment:
	*/
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
	/**
	*Name:最后登录时间
	*Comment:
	*/
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
	/**
	*Name:优先级
	*Comment:
	*/
    public int getPriority() {
        return this.priority;
    }
    
	/**
	*Name:优先级
	*Comment:
	*/
    public void setPriority(int priority) {
        this.priority = priority;
    }
    public boolean isSoftDelete() {
        return this.softDelete;
    }
    
	/**
	*Name:是否软删除
	*Comment:
	*/
    public void setSoftDelete(boolean softDelete) {
        this.softDelete = softDelete;
    }
	/**
	*Name:登录令牌
	*Comment:
	*/
    public String getAccessToken() {
        return this.accessToken;
    }
    
	/**
	*Name:登录令牌
	*Comment:
	*/
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }
	/**
	*Name:令牌失效时间
	*Comment:
	*/
    public Date getAccessTokenExpire() {
        return this.accessTokenExpire;
    }
    
	/**
	*Name:令牌失效时间
	*Comment:
	*/
    public void setAccessTokenExpire(Date accessTokenExpire) {
        this.accessTokenExpire = accessTokenExpire;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public List<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }




}


