package com.sunnsoft.sloa.db.vo;
// Generated by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * UserCollection generated by hbm2java
 */
public class UserCollection  implements java.io.Serializable {

	/**
	 *  serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	*Name:收藏id
	*Comment:收藏id
	*/
     private Long collectionId;
     private Mail mail;
	/**
	*Name:收藏人id
	*Comment:收藏人id
	*/
     private long userId;
	/**
	*Name:收藏人工作编号
	*Comment:收藏人工作编号
	*/
     private String workCode;
	/**
	*Name:收藏人的姓名
	*Comment:收藏人的姓名
	*/
     private String lastName;
	/**
	*Name:收藏时间
	*Comment:收藏时间
	*/
     private Date collectionTime;
	/**
	*Name:区别
	*Comment:区别是: 已发传阅人收藏的记录或是已收传阅人的收藏记录
	*/
     private String differentiate;

    public UserCollection() {
    }

	
    public UserCollection(long userId) {
        this.userId = userId;
    }
    public UserCollection(Mail mail, long userId, String workCode, String lastName, Date collectionTime, String differentiate) {
       this.mail = mail;
       this.userId = userId;
       this.workCode = workCode;
       this.lastName = lastName;
       this.collectionTime = collectionTime;
       this.differentiate = differentiate;
    }
   
	/**
	*Name:收藏id
	*Comment:收藏id
	*/
    public Long getCollectionId() {
        return this.collectionId;
    }
    
	/**
	*Name:收藏id
	*Comment:收藏id
	*/
    public void setCollectionId(Long collectionId) {
        this.collectionId = collectionId;
    }
    public Mail getMail() {
        return this.mail;
    }
    
    public void setMail(Mail mail) {
        this.mail = mail;
    }
	/**
	*Name:收藏人id
	*Comment:收藏人id
	*/
    public long getUserId() {
        return this.userId;
    }
    
	/**
	*Name:收藏人id
	*Comment:收藏人id
	*/
    public void setUserId(long userId) {
        this.userId = userId;
    }
	/**
	*Name:收藏人工作编号
	*Comment:收藏人工作编号
	*/
    public String getWorkCode() {
        return this.workCode;
    }
    
	/**
	*Name:收藏人工作编号
	*Comment:收藏人工作编号
	*/
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }
	/**
	*Name:收藏人的姓名
	*Comment:收藏人的姓名
	*/
    public String getLastName() {
        return this.lastName;
    }
    
	/**
	*Name:收藏人的姓名
	*Comment:收藏人的姓名
	*/
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
	/**
	*Name:收藏时间
	*Comment:收藏时间
	*/
    public Date getCollectionTime() {
        return this.collectionTime;
    }
    
	/**
	*Name:收藏时间
	*Comment:收藏时间
	*/
    public void setCollectionTime(Date collectionTime) {
        this.collectionTime = collectionTime;
    }
	/**
	*Name:区别
	*Comment:区别是: 已发传阅人收藏的记录或是已收传阅人的收藏记录
	*/
    public String getDifferentiate() {
        return this.differentiate;
    }
    
	/**
	*Name:区别
	*Comment:区别是: 已发传阅人收藏的记录或是已收传阅人的收藏记录
	*/
    public void setDifferentiate(String differentiate) {
        this.differentiate = differentiate;
    }




}


