package com.sunnsoft.sloa.db.dao;

import com.sunnsoft.sloa.db.vo.Hrmdepartment;
import org.gteam.db.dao.IBaseDAO;

import java.util.List;

// Generated by Hibernate Tools 3.4.0.CR1,modified by llade
/**
 * Home object for domain model class Hrmdepartment.
 * @see com.sunnsoft.sloa.db.vo.Hrmdepartment
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface HrmdepartmentDAO extends IBaseDAO {


	public abstract  Hrmdepartment findById(Integer id) ;
    
    public abstract  void save(Hrmdepartment transientInstance) ;
    
	public abstract  void delete(Hrmdepartment persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
