package com.sunnsoft.sloa.db.dao;
import org.gteam.db.dao.IBaseDAO;
import com.sunnsoft.sloa.db.vo.Menu;
// Generated by Hibernate Tools 3.4.0.CR1,modified by llade


import java.util.List;
/**
 * Home object for domain model class Menu.
 * @see com.sunnsoft.sloa.db.vo.Menu
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface MenuDAO extends IBaseDAO {


	public abstract  Menu findById(Long id) ;
    
    public abstract  void save(Menu transientInstance) ;
    
	public abstract  void delete(Menu persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
