package com.sunnsoft.sloa.db.dao;
import org.gteam.db.dao.IBaseDAO;
import com.sunnsoft.sloa.db.vo.UserInfo;
// Generated by Hibernate Tools 3.4.0.CR1,modified by llade


import java.util.List;
/**
 * Home object for domain model class UserInfo.
 * @see com.sunnsoft.sloa.db.vo.UserInfo
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface UserInfoDAO extends IBaseDAO {


	public abstract  UserInfo findById(Long id) ;
    
    public abstract  void save(UserInfo transientInstance) ;
    
	public abstract  void delete(UserInfo persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
