package com.sunnsoft.sloa.db.dao;
import org.gteam.db.dao.IBaseDAO;
import com.sunnsoft.sloa.db.vo.UserCollection;
// Generated by Hibernate Tools 3.4.0.CR1,modified by llade


import java.util.List;
/**
 * Home object for domain model class UserCollection.
 * @see com.sunnsoft.sloa.db.vo.UserCollection
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface UserCollectionDAO extends IBaseDAO {


	public abstract  UserCollection findById(Long id) ;
    
    public abstract  void save(UserCollection transientInstance) ;
    
	public abstract  void delete(UserCollection persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
