package com.sunnsoft.sloa.db.dao;

import com.sunnsoft.sloa.db.vo.UserMssage;
import org.gteam.db.dao.IBaseDAO;

import java.util.List;

// Generated by Hibernate Tools 3.4.0.CR1,modified by llade
/**
 * Home object for domain model class UserMssage.
 * @see com.sunnsoft.sloa.db.vo.UserMssage
 * @author Hibernate Tools
 * @author llade
 */
@SuppressWarnings("unchecked")
public interface UserMssageDAO extends IBaseDAO {


	public abstract  UserMssage findById(Long id) ;
    
    public abstract  void save(UserMssage transientInstance) ;
    
	public abstract  void delete(UserMssage persistentInstance) ;
    
    public abstract  List findByProperty(String propertyName, Object value) ;

}
